// Type declaration for the browser bundle generated by scripts/bundle-browser.cjs
// The actual file is generated directly into dist/stdlib-browser-bundle.js
export declare const STDLIB_FILES: Record<string, string>;
